dtask/scenarios/forms.py
from dtask import app
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, DateField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Optional
from os.path import join, isfile
import os


choice = [('display', 'Select options'),('first', 1), ('second', 2), ('third', 3), ('forth',4), ('fifth',5), ('tenth', 10)]
choicePCFiles = [('','')]
choiceIdxFiles = [('','')]

def get_files():
	currentPath = os.getcwd()
	compFilePath = join(currentPath, 'dtask/static/compfiles')
	files = [f for f in os.listdir(compFilePath) if isfile(join(compFilePath, f))]
	#print "COMPARE FILES: ", files
	#choiceFiles = [('Select File for comparision','Select File for comparision')]
	for file in files:
		if 'PC' in file or 'pc' in file:
			choicePCFiles.append((file, file))
		elif 'indx' in file:
			choiceIdxFiles.append((file, file))

	#return choiceFiles

class ScenariosForm(FlaskForm):
	"""docstring for HistScenarioForm"""
	default_scenario_set = BooleanField('Default Scenario Set', validators=[])
	scenario_set_name = StringField('Scenario set Name', validators=[Optional()])
	scenario_set_desc = TextAreaField('Scenario set Descriptions', validators=[Optional()])
	lock_back_period = SelectField('Lock Back Period', choices=choice)
	start_date = DateField('Start Date', validators=[DataRequired()], format='%d/%m/%Y')
	end_date = DateField('End Date', validators=[DataRequired()], format='%d/%m/%Y')
	effective_date = DateField('Effective Date', validators=[Optional()], format='%d/%m/%Y')
	expiry_date = DateField('Expiry Date', validators=[Optional()], format='%d/%m/%Y')
	liquidation_horizon = SelectField('Liquidation Horizon', choices=choice)
	liquidation_period = SelectField('Rankings per Up/Down Selection', choices=choice)
	
	
class RunAnalysisForm(FlaskForm):
	"""docstring for RunAnalysisForm"""
	get_files()
	currentPcdfFile = SelectField('Current PCDF File:', choices=choicePCFiles)
	previousPcdfFile = SelectField('Previous PCDF File:', choices=choicePCFiles)

	currentIdxFile = SelectField('Current Idx File:', choices=choiceIdxFiles)
	previousIdxFile = SelectField('Previous Idx File:', choices=choiceIdxFiles)

	compare_excel = SubmitField(label='Compare Excel')
	generate_excel = SubmitField(label='Generate Excel')

	

dtask/scenarios/controllers.py
from flask import render_template, Blueprint, request, make_response, flash
from dtask.scenarios.forms import ScenariosForm, RunAnalysisForm
from dtask import app
import pandas as pd
import subprocess
import pymssql
import os


##############################################################################
scenarios = Blueprint('scenarios', __name__, url_prefix='/scenarios')
##############################################################################


@scenarios.route('/runanalysis', methods=['GET', 'POST'])
def run_analysis():
	form = RunAnalysisForm()
	title = "Run Comparision Analysis"

	if request.method == 'POST' and form.validate_on_submit():
		# call R script
		if form.generate_excel.data:
			resp = callRScript()
			if resp == 0:
				flash ("Excel generated!!!")
				#return "EXCEL Generated!!"
				return (render_template('scenarios/run_analysis.html', form=form, title=title))

		# compare excel files
		elif form.compare_excel.data:
			curPcdfFile = form.currentPcdfFile.data
			prePcdfFile = form.previousPcdfFile.data
			curIdxFile = form.currentIdxFile.data
			preIdxFile = form.previousIdxFile.data

			if not (curPcdfFile and prePcdfFile and curIdxFile and preIdxFile):
				flash("please select the comparision files!!")
				return (render_template('scenarios/run_analysis.html', form=form, title=title))

			path = os.getcwd() + '/dtask/static/compfiles'
			preMonPCDF = pd.read_excel(os.path.join(path, prePcdfFile), sheetname = "Sheet1")
			newMonPCDF = pd.read_excel(os.path.join(path, curPcdfFile), sheetname = "Sheet1")
			preMonIdxDF = pd.read_excel(os.path.join(path, preIdxFile), sheetname = "Sheet1")
			newMonIdxDF = pd.read_excel(os.path.join(path, curIdxFile), sheetname = "Sheet1")

			preMonPCDF.reset_index(inplace = True)
			newMonPCDF.reset_index(inplace = True)
			preMonIdxDF.reset_index(inplace = True)
			newMonIdxDF.reset_index(inplace = True)
			preMonPCDF.rename(columns = {"index": "Date"}, inplace = True)
			newMonPCDF.rename(columns = {"index": "Date"}, inplace = True)
			preMonIdxDF.rename(columns = {"index": "Date"}, inplace = True)
			newMonIdxDF.rename(columns = {"index": "Date"}, inplace = True)

			missDF = preMonPCDF[~preMonPCDF.Date.isin(newMonPCDF.Date.values)]
			newDF = newMonPCDF[~newMonPCDF.Date.isin(preMonPCDF.Date.values)]

			# print missDF['Date']
			# print "=============="
			# print newDF['Date']
			rows = []
			newRows = []
			missRows = []
			if not newDF.empty:
				for index, row in newDF.iterrows():
					#print "ROW:  ", row
					date = row['Date']
					#print "Date: ", date
					driSeries = newMonIdxDF.loc[newMonIdxDF['Date'] == str(date), 'driver']
					#print driSeries
					driver = driSeries.values[0]
					#print "DRIVER: ", driver
					rank = makeAnalysisData(date, driver, newMonPCDF, 'New')
					rows.append(rank)
			if not missDF.empty:
				for index, row in missDF.iterrows():
					#print "ROW:  ", row
					date = row['Date']
					#print "Date: ", date
					driSeries = preMonIdxDF.loc[preMonIdxDF['Date'] == str(date), 'driver']
					driver = driSeries.values[0]
					#print "DRI: ", driver
					#print "DRIVER: ", driver
					rows.append(makeAnalysisData(date, driver, preMonPCDF, 'Missing'))


			return render_template("scenarios/disp_analysis.html",rows = rows)
		else:
			pass

	if form.errors:
		for error_field, error_message in form.errors.iteritems():
			flash("Field : {field}; error : {error}".format(field=error_field, error=error_message))

	return (render_template('scenarios/run_analysis.html', form=form, title=title))


@scenarios.route('/createMBSD', methods=['GET', 'POST'])
def createMBSD():
	form = ScenariosForm()
	title = "create MBSD scenario Data"
	choices = {'first': 1, 'second': 2, 'third': 3, 'fourth': 4, 'fifth': 5, 'tenth': 10}

	if request.method == 'POST' and form.validate_on_submit():
		bus_dt = form.start_date.data
		liq_period = choices.get(request.form.get('liquidation_period'), 0)
		look_back_period = choices.get(request.form.get('lock_back_period'), 0)

		cur = getConnection()
		#cur.execute("select * from yld_crv_hist_v")
		#cur.execute("EXEC s_SGD_CPA_raw_data_R @bus_dt = '1990-01-10', @liq_period = 10, @look_back_period = 5")
		cur.execute("EXEC s_SGD_CPA_raw_data_R @bus_dt = '{}', @liq_period = {}, @look_back_period = {}".format(bus_dt, liq_period, look_back_period))

		rows = cur.fetchall();

		# print app.config['USERNAME']
		# print app.config['PASSWORD']
		# print rows
		return render_template("scenarios/disp_create.html",rows = rows)

	return (render_template('scenarios/create.html', form=form, title=title))


@scenarios.route('/createBSD', methods=['GET', 'POST'])
def createBSD():
	form = ScenariosForm()
	title = "create BSD scenario Data"
	return (render_template('scenarios/create.html', form=form, title=title))


@scenarios.route('/createNSE', methods=['GET', 'POST'])
def createNSE():
	form = ScenariosForm()
	title = "create NSE scenario Data"
	return (render_template('scenarios/create.html', form=form, title=title))


def callRScript():
	rspt = os.getcwd() + '/dtask/myrscript.R'
	res = subprocess.check_call(['Rscript', rspt], shell = False)
	return res

def getConnection():
	con = pymssql.connect(  app.config['HOSTNAME'],
								app.config['USERNAME'],
								app.config['PASSWORD'],
								app.config['DBNAME'],
								app.config['PORT'])

	cursor = con.cursor()

	return cursor


def makeAnalysisData(date, driver, pcFile, sln):
	pcFile.sort_values(by=[str(driver.lower())], ascending = True, inplace = True)
	dfLength = len(pcFile.index)

	#print "dfLength: ", dfLength
	#print date
	# get rank
	rank = getRank(pcFile, driver, date, dfLength)
	rowNumTop = rank + 1
	rowNumBottom = "-{}".format(dfLength - rank) 

	#print "rowNumTop: ", rowNumTop
	#print "rowNumBottom: ", rowNumBottom
	#print "DATE: {}, DRIVER: {}, RANK: {}".format(date, driver, rowNumTop)
	return (str(sln),
				str(date)[:10],
				str(rowNumTop),
				str(rowNumBottom),
				str(driver)
				)

def getRank(pcFile, driver, date, dfLength):
    rank = ''

    r = pcFile.loc[pcFile['Date'] == date, 'Date']
    #print r
    rank = r.index.values[0]
    return rank

dtask/templates/scenarios/create.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}

{% block scripts %}
    {{ super() }}

    <script>
      $( function() {
        $( ".dtpick" ).datepicker();
      } );
    </script>

{% endblock %}
{% block  content %}
{% include 'macros.html' %}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well well-lg" style="background-color: lightgrey">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="row">
                        {% if "create MBSD" in title %}
                            <div align="center">
                                <u><h2>MBSD Scenario Generation</h2></u>
                            </div>
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('scenarios.createMBSD')}}">
                        {% endif %}
                        {% if "create BSD" in title %}
                            <div align="center">
                                <u><h2>BSD Scenario Generation</h2></u>
                            </div>
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('scenarios.createBSD')}}">
                        {% endif %}
                        {% if "NSE" in title %}
                            <div align="center">
                                <u><h2>NSE Scenario Generation</h2></u>
                            </div>
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('scenarios.createNSE')}}">
                        {% endif %}

                            {{form.hidden_tag()}}

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.default_scenario_set, with_label=False, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.scenario_set_name, with_label=True, placeholder="scenario name", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.scenario_set_desc, with_label=True, placeholder="description", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.lock_back_period, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.start_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.end_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.effective_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.expiry_date, with_label=True, placeholder="mm/dd/yyyy", class_="dtpick")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.liquidation_horizon, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.liquidation_period, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 50px">
                                <div class="col-md-4"></div>
                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary btn-block">GENERATE</button>
                                </div>
                            </div>
                            {# {{form.errors}} #}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

dtask/templates/scenarios/disp_analysis.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}
{% block scripts %}
    {{ super() }}

    <script type="text/javascript">
      $(document).ready(function(){
         var table = $('#urls').DataTable();
         $("#urls thead th").each( function ( i ){
            var name = table.column( i ).header();
            var spanelt = document.createElement( "button" );
            spanelt.innerHTML = name.innerHTML;

            $(spanelt).addClass("colvistoggle");
            $(spanelt).attr("colidx", i);

            $(spanelt).on( 'click', function (e) {
               e.defaultPrevented();
               // get column API object
               var column = table.column( $(this).attr('colidx') );
               // toggle the visivility
               column.visible( ! column.visible() );
            });
            $("#colvis").append($(spanelt));
         });
      });

    </script>

{% endblock %}
{% block  content %}

<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div class="well well-lg" style="width:100%;overflow-x: auto;overflow-y: auto;">
         <div class="table-responsive">
            <table id="urls" name='urls' class="display" cellspacing="0" width="100%">
               <thead>
                  <th>Record Type</th>
                  <th>Date</th>
                  <th>Rank from Top</th>
                  <th>Rank from Bottom</th>
                  <th>Driver</th>
               </thead>
               <tfoot>
                  <th>Record Type</th>
                  <th>Date</th>
                  <th>Rank from Top</th>
                  <th>Rank from Bottom</th>
                  <th>Driver</th>
               </tfoot>
               <tbody>
                  {%- for row in rows %}
                     <tr>
                        <td>{{row[0]}}</td>
                        <td>{{row[1]}}</td>
                        <td>{{row[2]}}</td>
                        <td>{{row[3]}}</td>
                        <td>{{row[4]}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>

{% endblock %}

dtask/templates/scenarios/disp_create.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}
{% block scripts %}
    {{ super() }}

    <script type="text/javascript">
      $(document).ready(function(){
         var table = $('#urls').DataTable();
         $("#urls thead th").each( function ( i ){
            var name = table.column( i ).header();
            var spanelt = document.createElement( "button" );
            spanelt.innerHTML = name.innerHTML;

            $(spanelt).addClass("colvistoggle");
            $(spanelt).attr("colidx", i);

            $(spanelt).on( 'click', function (e) {
               e.defaultPrevented();
               // get column API object
               var column = table.column( $(this).attr('colidx') );
               // toggle the visivility
               column.visible( ! column.visible() );
            });
            $("#colvis").append($(spanelt));
         });
      });

    </script>

{% endblock %}
{% block  content %}

<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div id="colvis"></div>
   </div>
</div>
<div class="row">
   <div class="col-lg-1"></div>
   <div class="col-lg-10">
      <div class="well well-lg" style="width:100%;overflow-x: auto;overflow-y: auto;">
         <div class="table-responsive">
            <table id="urls" name='urls' class="display" cellspacing="0" width="100%">
               <thead>
                  <td>Date</td>
                  <td>y1</td>
                  <td>y2</td>
                  <td>y3</td>
                  <td>y5</td>
                  <td>y7</td>
                  <td>y10</td>
                  <td>y20</td>
                  <td>y30</td>
               </thead>
               <tfoot>
                  <td>Date</td>
                  <td>y1</td>
                  <td>y2</td>
                  <td>y3</td>
                  <td>y5</td>
                  <td>y7</td>
                  <td>y10</td>
                  <td>y20</td>
                  <td>y30</td>
               </tfoot>
               <tbody>
                  {%- for row in rows %}
                     <tr>
                        <td>{{row[0]}}</td>
                        <td>{{row[1]}}</td>
                        <td>{{row[2]}}</td>
                        <td>{{row[3]}}</td>
                        <td>{{row[4]}}</td>
                        <td>{{row[5]}}</td>
                        <td>{{row[6]}}</td>
                        <td>{{row[7]}}</td>
                        <td>{{row[8]}}</td>
                     </tr>
                  {% endfor %}
               </tbody>
            </table>
         </div>
      </div>
   </div>
</div>

{% endblock %}

dtask/templates/scenarios/run_analysis.html
{% extends 'base.html' %}
{% import "macros.html" as macros %}

{% block scripts %}
    {{ super() }}

{% endblock %}
{% block  content %}
{% include 'macros.html' %}

<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
        <div class="well well-lg" style="background-color: lightgrey">
            <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                    <div class="row">
                        <div align="center">
                            <u><h2>Provide details for comparision analysis</h2></u>
                        </div>
                        {% if "Run" in title %}
                            <form class="form-horizontal" method="POST" name="url" action="{{url_for('scenarios.run_analysis')}}">
                        {% endif %}

                            {{form.hidden_tag()}}

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.currentPcdfFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.previousPcdfFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.currentIdxFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-11">
                                    {{macros.form_field(form.previousIdxFile, with_label=True, placeholder="", class_="form-control")}}
                                </div>
                            </div>

                            <div class="row" style="padding-top: 50px">
                                <div class="col-md-3"></div>
                                <div class="col-md-3" >
                                        {{ form.compare_excel }}
                                </div>
                                <div class="col-md-4">
                                        {{ form.generate_excel }}
                                </div>
                            </div>
                            {# {{form.errors}} #}
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}